fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0 # Replace with the latest version
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      args: [--convention=google]
