---
title: "Predict 2023 dengue cases"
author: "Wesley GOI"
date: "2024-11-01"
output: html_document
---

```{r}
suppressPackageStartupMessages(library(argparse))
suppressPackageStartupMessages(library(yaml))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(INLA))
```


```{r readConf}
parse_config <- function(yaml_file, response = "cases") {
  yaml_data <- yaml.load_file(yaml_file)
  hyperparams <- yaml_data$model$hyperparameters
  build_feature_str <- function(f) glue::glue("f(inla.group({f$name}, n = {f$bins}), model = '{f$model}', scale.model = {as.character(f$scale_model)}, hyper = hyperparameters)")
  build_random_effect_str <- function(re) glue::glue("f({re$name}, model = '{re$model}', cyclic = {re$cyclic}, hyper = hyperparameters)")
  formula_str <- str_c(lapply(yaml_data$features, build_feature_str), collapse = " + ")
  random_effects_str <- str_c(lapply(yaml_data$random_effects, build_random_effect_str), collapse = " + ")
  hyperparameters <- list(prec = list(prior = hyperparams[[1]]$prec$prior, param = unlist(hyperparams[[1]]$prec$param)))
  offset = glue::glue("offset({yaml_data$model$inla$offset})")
  full_formula <- as.formula(glue::glue("{response} ~ 1 + {formula_str} + {random_effects_str} + {offset}"))

  list(
    formula = full_formula,
    inla_model = yaml_data$model$inla,
    hyperparameters = hyperparameters,
    input_s = yaml_data$input_file,
    train_start_time = yaml_data$train$start_time,
    train_end_time = yaml_data$train$end_time,
    test_start_time = yaml_data$test$start_time,
    test_end_time = yaml_data$test$end_time
  )
}
config = parse_config("/home/wesley/github/etheleon/national_analysis/dengue/models/INLA/config.yaml")
```

Sanity check to see if the temperature feature makes sense.

```{r}
library(ggplot2)

library(stringr)

df <- df %>%
  mutate(newdate = paste0(year, str_pad(eweek, width = 2, pad = "0")))
```

```{r}

ggplot(df, aes(newdate, max_t_scale_12_wk_avg_0)) + geom_point()
```


```{r split, echo=FALSE}
get_dataset <- function(csv_file_path = "/workplace/data.csv",
                        train_start,
                        train_end,
                        pred_start,
                        pred_end,
                        horizon = 0) {

  create_newdate <- function(date_s){
    as.integer(paste0(isoyear(date_s), str_pad(isoweek(date_s), width = 2, pad = "0")))
  }
  readr::read_csv(csv_file_path) |>
    mutate(yearmonth = as.integer(paste0(year, str_pad(eweek, width = 2, pad = "0")))) |>
    mutate(cases_actual = cases) |>
    mutate(cases = case_when(
      yearmonth >= create_newdate(train_start) & yearmonth < create_newdate(train_end) ~ cases,
      yearmonth >= create_newdate(pred_start) & yearmonth < create_newdate(pred_end) ~ NA
    ))
}

datasets = get_dataset("/home/wesley/github/etheleon/national_analysis/data.csv", config$train_start_time, train_end=config$train_end_time, config$test_start_time, config$test_end_time)
```

```{r}
train <- function(df, formula, inla_m) {
    model <- inla(formula,
        family = inla_m$family,
        control.inla = inla_m$control.inla,
        control.predictor = inla_m$control$predictor,
        control.compute = inla_m$control$compute,
        control.fixed = inla_m$control$fixed,
        num.threads = inla_m$num.threads,
        verbose = inla_m$verbose,
        data = df
    )
    model
}
model = train(datasets, formula=config$formula, inla_m=config$inla_model)
```

```{r}
summary(model)
```


```{r}

fitted_df <- data.frame(
  date = datasets$date, # Change to your forecast dates
  mean = model$summary.fitted.values$mean,  # Replace with your actual forecast means
  lower = model$summary.fitted.values$`0.025quant`, # Lower bound (95% CI)
  upper = model$summary.fitted.values$`0.975quant`  # Upper bound (95% CI)
)

ggplot() +
  geom_line(data = fitted_df, aes(x = date, y = mean), color = "blue") +
  geom_line(data = datasets, aes(x = date, y = cases_actual), color = "red") +
  geom_ribbon(data = fitted_df, aes(x = date, ymin = lower, ymax = upper), alpha = 0.5, fill = "darkgrey") +
  labs(title = "Time Series Forecast with INLA (Weekly)",
       x = "Date",
       y = "Cases",
       color = "Type") +
  scale_color_manual(values = c("Observed" = "blue", "Forecast" = "red"))
  # theme_minimal()
```



