model:
  horizon: 0
  hyperparameters: 
    - prec:
        prior: 'pc.prec'
        param: [0.5, 0.01]
features:
  - name: time_since_switch
    variable_type: group
    bins: 18
    model: 'rw2'
    scale_model: true
  - name: max_t_scale_12_wk_avg_0
    variable_type: group
    model: 'rw2'
    scale_model: true
  - name: nino34_12_wk_avg_4
    variable_type: group
    bins: 12
    model: 'rw2'
    scale_model: true
  - name: days_no_rain_12_wk_total_0
    variable_type: group
    model: 'rw2'
    scale_model: true
random_effects:
  - name: year_index
    model: 'iid'